version: '2'

services:
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb
    container_name: mariadb
    networks:
      - inception_network
    volumes:
      - mariadb_volume:/var/lib/mysql
    secrets:
      - db_root_password
      - db_password
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
      - MYSQL_PASSWORD_FILE=/run/secrets/db_password
    restart: always

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress_volume:/var/www/html
    networks:
      - inception_network
    secrets:
      - db_password
      - wp_admin_password
      - wp_user_password
    environment:
      - WP_URL=${WP_URL}
      - WP_DB_HOST=mariadb
      - WP_DB_NAME=${MYSQL_DATABASE}
      - WP_DB_USER=${MYSQL_USER}
      - WP_DB_PASSWORD_FILE=/run/secrets/db_password
      - WP_TITLE=${WP_TITLE}
      - WP_ADMIN_USER=${WP_ADMIN_USER}
      - WP_ADMIN_PASSWORD_FILE=/run/secrets/wp_admin_password
      - WP_ADMIN_MAIL=${WP_ADMIN_MAIL}
      - WP_USER=${WP_USER}
      - WP_USER_MAIL=${WP_USER_MAIL}
      - WP_USER_PASSWORD_FILE=/run/secrets/wp_user_password
    restart: always

  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress_volume:/var/www/html
    networks:
      - inception_network
    restart: always

volumes:
  mariadb_volume:
    driver: local
    driver_opts:
      type: none
      device: /home/${LOGIN}/data/mariadb
      o: bind
  wordpress_volume:
    driver: local
    driver_opts:
      type: none
      device: /home/${LOGIN}/data/wordpress
      o: bind

networks:
  inception_network:
    driver: bridge

secrets:
  db_root_password:
    file: ./secrets/db_root_password.txt
  db_password:
    file: ./secrets/db_password.txt
  wp_admin_password:
    file: ./secrets/wp_admin_password.txt
  wp_user_password:
    file: ./secrets/wp_user_password.txt
